### ISSUE TITLE
Share Schema of Data 

### ISSUE THREAD

**Issue by fahadsultan** [gcwarren/LanguageStatusVisualizationProject#4]
Post schema (column names) of the dataset you are looking to collect / scrape in reply to this. 

I see many CSV files in the repo. Which ones are you planning to use and how? 

Schedule a time on calendly to sit down and discuss progress.

**Comment by gcwarren** [comment]
Merge _wiki_languages_2.csv (lang, family, dialect, iso3code, speakers_str, regions, official_language, recognized_minority_language)_ with Extinct languages - DATA SUMMARY.csv (name, speakers, degree_of_endangerment) left on lang and right on name.

**Comment by fahadsultan** [comment]
Three datasets, two scrapers: 
1. [Languages by Region](https://github.com/gcwarren/LanguageStatusVisualizationProject/blob/main/languages_by_region_scraper.ipynb)
2. [wiki_languages.csv](wiki_languages.csv) and [scraper](scraper.ipynb)
3. UNESCO data: Extinct languages.csv
